services:
    hmp_kuma_extra.twig.content_twig_extension:

        class: Hmp\KumaExtraBundle\Twig\ContentTwigExtension
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    hmp_kuma_extra.twig.form_twig_extension:
        class: Hmp\KumaExtraBundle\Twig\FormTwigExtension
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    hmp_kuma_extra.twig.form_type_extension:
        class: Hmp\KumaExtraBundle\Form\Extensions\ExtraArgsTypeExtension
        tags:
          - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

