services:
    hmp_content_twig_extension:
        class: Hmp\KumaExtraBundle\Twig\ContentTwigExtension
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }
