name: Copy
context: messages
types:
    - { name: "Message", class: Hmp\KumaExtraBundle\Entity\PageParts\MessagePagePart }
    - { name: "Rich Text Message", class: Hmp\KumaExtraBundle\Entity\PageParts\RichTextMessagePagePart }
